### ISSUE TITLE
Añadir tiempos

### ISSUE THREAD

**Issue by IronSenior** [IronSenior/Jorge-TelegramBot-f1#1]
Hay que crear una funcion que permita añadir tu tiempo de la ULTIMA carrera.
La función tendrá como entrada la id del jugador, la id del chat y el tiempo con el formato M:S:MM, guardará este en la base de datos y enviará un mensaje diciendo que lo has hecho bien.

**Comment by AdoenLunnae** [comment]
Ya está subida la función, mañana la testeo y si funciona cierro.

**Comment by IronSenior** [comment]
Ya la he probado yo, solo he cambiado dos cosas que no tienen importancia (casa del path) y funciona perfectamente, comentala para que los demás puedan entenderla.
