### ISSUE TITLE
Revisión de tiempos

### ISSUE THREAD

**Issue by IronSenior** [IronSenior/Jorge-TelegramBot-f1#17]
Haz una función que revise si un usuario tiene un tiempo en la ultima carrera.
La función recibirá la id del usuario (uid) y el id del chat (cid) y devolverá True en caso de que si tenga tiempo y False en caso de que no tenga tiempo asignado.

**Comment by cyberh99** [comment]
@IronSenior Puedes hacer que retorne el tiempo si lo tiene y directamente lo metes dentro de @bot.send_message
