### ISSUE TITLE
Gran encargo

### ISSUE THREAD

**Issue by IronSenior** [IronSenior/Jorge-TelegramBot-f1#18]
La creación de competiciones no me acaba de convencer. Quiero que el comando join_in desaparezca. Ahora cuando se comience una competición saldrá un mensaje con una imagen que te pasaré más adelante.

Después de ese mensaje saldrá un teclado con todos los equipos de f1 para que te puedas unir a uno, cada equipo debe tener un máximo de 2 jugadores y debe salir el número de jugadores junto al nombre (Ejemplo: Mclaren (0/2)). Cuando pulses el botón este número debe cambiar y debe meterse en la base de datos el usuario (como estaba hecho en join_in pero añadiendo el equipo también como un nuevo elemento del json). El teclado debe actualizarse por lo tanto. 

Busca también si podemos hacer que ese mensaje se quede anclado sin que lo tenga que hacer el usuario,
Vas a ser la única persona que va a tocar el bot.py además de yo (tengo mucho trabajo y quiero terminar este bot lo antes posible). 

Si tienes cualquier duda preguntame, yo ya he trabajado con teclados en  la hackathon y te puedo ayudar en muchas cosas (además de hacer cadenas de preguntas y demás). Los teclado crealos en un archivo a parte en libs que se llame teclados.py (Mira el repositorio de eventbot si tienes dudas de sintaxis, no está comentado pero creo que lo entenderás bien).

Antes de hacer el push revisa todos los commits y dejame que revise el código. :)
Si es demasiado dimelo y se lo encargo a Hector o a Alvaro.

**Comment by IronSenior** [comment]
Adjunto a Hector de ayuda que alomejor es demasiado trabajo, os coordinais como querais.

**Comment by Pablorg99** [comment]
Es mi oportunidad para aprender a manejarme con lo que es la API de Telegram. Creo que puedo acabar haciendolo con la ayuda, depende de la prisa que tengas, me pondré el martes de esta semana seguramente. En la hackathon no manejé la api, estuvo Álvaro con eso y yo con Francis y los json, pero le echaré ganas.

**Comment by IronSenior** [comment]
@Pablorg99 No te preocupes, prisa ninguna

**Comment by cyberh99** [comment]
@Pablorg99 Eso nos los quitamos en un momento, yo te explico como funciona los de los teclados, que no es nada complejo, simplemente es tener en cuenta un par de cosillas.  :-)
