### ISSUE TITLE
Buscar imagen de cada circuito

### ISSUE THREAD

**Issue by IronSenior** [IronSenior/Jorge-TelegramBot-f1#20]
Hay que recolectar una url de una imagen de cada circuito (el mapa) para los mensajes de próxima carrera. Teneis que acortarla y ponedla como comentario de esta issue. Mirad antes de buscar un gp para que no me deis todos el mismo circuito.

**Comment by RexusWolf** [comment]
Ok tio

**Comment by RexusWolf** [comment]
[CIRCUITOS_F1.pdf](https://github.com/IronSenior/Jorge-TelegramBot-f1/files/1837370/CIRCUITOS_F1.pdf)

Ahí están TODOS los circuitos. Enjoy.
