### ISSUE TITLE
Mensajes especiales.

### ISSUE THREAD

**Issue by IronSenior** [IronSenior/Jorge-TelegramBot-f1#24]
Hay que diseñar mensajes especiales para:

1. El podium de cada carrera.
2. La clasificación del campeonato.
3. Podium final de la competición.
4. Revisad también el mensaje de información sobre la carrera.

Deben estar adornados, busca como meter emoticonos y demás.
Poneos de acuerdo en quien hace cual.

**Comment by RexusWolf** [comment]
Oh, I've just seen this issue I'm sorry :) (I'm kidding, I'll push it on Sunday)
