### ISSUE TITLE
Admin #2

### ISSUE THREAD

**Issue by IronSenior** [IronSenior/Jorge-TelegramBot-f1#25]
Esta tarea va unida a Admin #1 y a Chat privado.

Hay que diseñar todo el menú del administrador. Este menú debe hacer lo siguiente:

1. Mostrar teclado con todas las competiciones en las que ese usuario sea Admin
2. Una vez elegida la competición mostrará un menú de opciones disponibles: Penalizar jugador, Nombre, Eliminar.
3. Cada opción tiene un menú diferente: el de penalizar mostrará todos los usuarios de la competición y después las penalizaciones posibles (2, 5, 10 y 15); El de editar dejará cambiar el nombre de la competición; El de eliminar deberá mostrar otro mensaje para confirmar.

Cualquier duda consultadla en esta issue.

**Comment by IronSenior** [comment]
@AdoenLunnae Falta un detallito, cuando penalizas a alguien no te lo confirma de ninguna manera.
Me gustaria que enviara un mensaje por el grupo diciendo quien ha sido penalizado y con cuanto.

**Comment by AdoenLunnae** [comment]
Hecho
