### ISSUE TITLE
BUGS

### ISSUE THREAD

**Issue by IronSenior** [IronSenior/Jorge-TelegramBot-f1#27]
Quiero que probeis al máximo el bot y encontreis todos los bugs.
Probad todo lo que se os ocurra y más.
Cuando encontreis alguno, ponedlo en un comentario de esta issue (aunque sea una tonteria)

**Comment by IronSenior** [comment]
@AdoenLunnae no se puede penalizar, pero creo que es porque no hemos adaptado la funcion de penalización que habia antes para que funcione con el nuevo sistema. Lo haré yo.

**Comment by AdoenLunnae** [comment]
Lo del /time está arreglado, era un error al coger argumentos. A mi si me deja penalizar.

**Comment by AdoenLunnae** [comment]
Arreglado tambien lo de penalizar a alguien sin tiempo(o que está desclalificado).

**Comment by IronSenior** [comment]
@AlexTheMagnus Cuando hay menos de 3 participantes petan las funciones de clasificación, hay que arreglar eso.

**Comment by IronSenior** [comment]
@AdoenLunnae @AlexTheMagnus cuando mandamos la clasificación del campeonato en vez del nombre salen unos números (que supongo son las ids). Hay que arreglarlo y que salgan los nombres
